export const apiResources = {
    login: 'login',
    registerUser: 'RegisterUser',
    changePassword: 'ChangePassword',
    updateProfile: 'UpdateProfile',
    forgotPassword: 'ForgotPassword',
    getRoles: 'GetRoles',
    getRolesById: 'GetRoles',
    getCoursesByStudentId: 'student/school/course/list',
    getAttendanceById: 'GetAttendanceById',
    getLastDayAttendanceByStudentId: 'GetLastDayAttendanceById',
    getAttendanceByCourseId: 'GetAttendanceByCourseId',
    getCoursesByTeacherId: 'teacher/school/course/list',
    getStudentsByTeacherId: 'GetStudentsByTeacherId',
    getAllHolidays: 'GetAllHolidays',
    getAttendanceByStudentIdandCourseId: 'GetAttendanceByStudentIdandCourseId',
    getAttendanceByStudentIdandDate: 'student/course/attendance/list',
    getStudentAttendanceDetails: 'student/attendance/details',
    getSchoolsMappedToTeacher: 'teacher/school/list',
    updateStudentAcknowledgement: 'student/course/attendance/mark',
    getAttendanceReportData: 'GetAttendanceReportData',
    getStudentsAttendanceByCourseandDate: 'teacher/school/course/students/list',
    updateStudentAttendanceByTeacher: 'teacher/school/course/attendance/mark',
    updateProfilePic: 'student/upload/profile'
};
