export const apiResources = {
    login: 'login',
    registerUser: 'RegisterUser',
    changePassword: 'ChangePassword',
    updateProfile: 'UpdateProfile',
    forgotPassword: 'ForgotPassword',
    getRoles: 'GetRoles',
    getRolesById: 'GetRoles',
    getCoursesByStudentId: 'GetCoursesById',
    getAttendanceById: 'GetAttendanceById',
    getLastDayAttendanceByStudentId: 'GetLastDayAttendanceById',
    getAttendanceByCourseId: 'GetAttendanceByCourseId',
    getCoursesByTeacherId: 'GetCoursesByTeacherId',
    getStudentsByTeacherId: 'GetStudentsByTeacherId',
    getAllHolidays: 'GetAllHolidays',
    getAttendanceByStudentIdandCourseId: 'GetAttendanceByStudentIdandCourseId',
    getAttendanceByStudentIdandDate: 'GetAttendanceByStudentIdandDate',
    getSchoolsMappedToTeacher: 'GetSchoolsMappedToTeacher',
    updateStudentAcknowledgement: 'UpdateAcknowledgement',
    getAttendanceReportData: 'GetAttendanceReportData',
    getStudentsAttendanceByCourseandDate: 'GetStudentsAttendanceByCourseandDate',
    updateStudentAttendanceByTeacher: 'UpdateStudentAttendanceByTeacher'
};
